version: '3.8'

services:
  spa:
    build: ./spa
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./spa/:/usr/src/spa/
    ports:
      - 8000:8000
    env_file:
      - ./.env