# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  tests:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          command: |
            sudo apt install python3.8-venv
      - run:
          command: |
            . spa/checksenv/bin/activate
      - run:
          command: |
            sudo pip install -r spa/requirements.txt
      - run:
          name: Running tests
          command: |
            python3 spa/manage.py test
      - store_artifacts:
          path: test-reports/
          destination: spa

workflows:
  build-workflow:
    jobs:
      - tests